name: metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_GRAINED_TOKEN }}
          config_timezone: Europe/Helsinki
          template: terminal
          base: header, metadata, repositories, community, activity
          repositories_forks: true
          plugin_isocalendar: yes
          plugin_achivements: yes
          plugin_rss: yes
          plugin_rss_source: "777.tf/blog/index.xml"
